services:
  nexus:
    image: sonatype/nexus3:3.76.1
    container_name: nexus
    restart: unless-stopped

    ports:
      - "8081:8081"

    volumes:
      - nexus3-data:/nexus3-data

    environment:
      INSTALL4J_ADD_VM_PARAMS: >-
        -Xms1g
        -Xmx2g
        -XX:MaxDirectMemorySize=2g
        -Djava.util.prefs.userRoot=/nexus3-data/javaprefs

volumes:
  nexus3-data: